### ISSUE TITLE
Is the awsvpn overlay no longer necessary?

### ISSUE THREAD

**Issue by danwdart** [ivankovnatsky/nixos-config#50]
I noticed you deleted the overlay, is it no longer necessary? Thanks

**Comment by ivankovnatsky** [comment]
Hey, it wasn't mine, this guy did it: https://github.com/ymatsiuk/awsvpnclient. Should be working and recent more or less.

**Comment by danwdart** [comment]
Alright, I've figured something out. Thanks!

**Comment by ivankovnatsky** [comment]
> I noticed you deleted the overlay

Ah, you meant a file in my repo, did't get at first. Stopped using it and I guess I removed it.
